Create DATABASE Livraria;

/*TABELA*/

CREATE TABLE LIVROS(
NOMEDOLIVRO VARCHAR(30),
NOMEDOAUTOR VARCHAR(30),
SEXO CHAR(1),
NUMERODEPAGINAS INT(5),
NOMEDAEDITORA VARCHAR(30),
VALORDOLIVRO FLOAT(5,2),
UF CHAR(2),
ANOPUBLICACAO INT(4)
);

/*INSERINDO DADOS*/

INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.90,'RJ',2009);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('SQL para leigos','Joao Nunes','M',450,'Addison',98,'SP',2018);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('Pessoas Efitivas','Eduardo Santos','M',390,'Beta',78.99,'RJ',2018);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('Habitos Saudaveis','Eduardo Santos','M',630,'Beta',150.98,'RJ',2019);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78.98,'ES',2011);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130.98,'RS',2018);
INSERT INTO LIVROS(NOMEDOLIVRO,NOMEDOAUTOR,SEXO,NUMERODEPAGINAS,NOMEDAEDITORA,VALORDOLIVRO,UF,ANOPUBLICACAO)VALUES('O poder da mente','Clara Mafra','F',120,'Continetal',56.58,'RS',2017);

/*COMANDOS PARA O PROGRAMADO*/

/*Trazer todos os dados.*/

SELECT * FROM LIVROS;

/*Trazer o nome do livro e o nome da editora*/

SELECT NOMEDOLIVRO, NOMEDAEDITORA FROM LIVROS;

/*Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino*/

SELECT NOMEDOAUTOR,NOMEDOLIVRO,UF FROM LIVROS
WHERE SEXO='M';

/*Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino.*/

SELECT NOMEDOAUTOR,NOMEDOLIVRO, NUMERODEPAGINAS FROM LIVROS
WHERE SEXO='F';

/*Trazer os valores dos livros das editoras de São Paulo*/

SELECT VALORDOLIVRO FROM LIVROS
WHERE UF ='SP';

/*Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).*/


SELECT NOMEDOLIVRO, NOMEDOAUTOR, SEXO,UF FROM LIVROS
WHERE SEXO='M' AND (UF='SP'OR UF='RJ') ;